name: DevOpsHub Image builder

on:
  workflow_dispatch:

jobs:
  repository-checkout:
    runs-on: ubuntu-latest
    environment: image_builder
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3
      
    - name: DevOpsHub_container_files checkout
      uses: actions/checkout@v2
      with:
        repository: brunohigino06/DevOpsHub_container_files
        path: DevOpsHub_container_files

    - name: Upload repository artifact
      uses: actions/upload-artifact@v3
      with:
        name: repo-files
        path: |
          .
          ./DevOpsHub_container_files

  docker_hub_login:
    runs-on: ubuntu-latest
    needs: repository-checkout
    environment: image_builder
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

  build_and_push:
    runs-on: ubuntu-latest
    needs: [repository-checkout, docker_hub_login]
    environment: image_builder
    steps:
    - name: Download repository artifact
      uses: actions/download-artifact@v3
      with:
        name: repo-files
        path: .

    - name: Build and push Docker image
      run: ls -a