name: DevOpsHub Image builder
on:
  workflow_dispatch:

jobs:
  repository-checkout:
    runs-on: ubuntu-latest
    environment: image_builder
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: DevOpsHub_container_files checkout
      uses: actions/checkout@v2
      with:
        repository: brunohigino06/DevOpsHub_container_files
        path: container_repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
 
  docker_hub_login:
    runs-on: ubuntu-latest
    needs: repository-checkout
    environment: image_builder
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
  
  build_and_push:
    runs-on: ubuntu-latest
    needs: docker_hub_login
    environment: image_builder
    steps:
    - name: test folder location
      run: ls

    - name: test folder location
      run: pwd
