name: BlogDevOpsHub Workflow

on:
  workflow_dispatch:

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    environment: terragrunt
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout terragrunt action
        uses: actions/checkout@v2
        with:
          repository: brunohigino06/github-actions
          path: github-actions

      - name: Checkout BlogDevOpsHub repo
        uses: actions/checkout@v2
        with:
          repository: brunohigino06/BlogDevOpsHub
          path: BlogDevOpsHub
          
      - name: Terragrunt Plan
        uses: ./github-actions/terragrunt
        with:
          command: plan
